#
# Autor: Antonio Marcos de Souza Santos
# Cargo: Developer Full Stack
# Data: 07/05/2026
#

server.forward-headers-strategy=framework

springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api/v3/api-docs

cors.allowed.origins=http://localhost:5173,http://134.209.164.87:7001,https://facilitedigital.com.br